import React from 'react';
import { Helmet } from 'react-helmet-async';
import { ExternalLink } from 'lucide-react';

export default function TermsOfService() {
    return (
        <React.Fragment>
            <Helmet>
                <title>Terms of Service | BarcodesMaker.com</title>
                <meta name="description" content="View the BarcodesMaker.com Terms of Service. Understand your rights and limitations when using our free barcode and QR code generator." />
                <link rel="canonical" href="https://barcodesmaker.com/terms-of-service" />
            </Helmet>

            <section className="relative pt-32 pb-20 md:pt-48 md:pb-32 overflow-hidden">
                <div className="absolute top-0 right-0 w-[600px] h-[600px] bg-cyber-blue/10 blur-[150px] -z-10 rounded-full opacity-30"></div>

                <div className="container mx-auto px-6 relative max-w-4xl">
                    <div className="flex items-center gap-4 mb-12">
                        <div className="w-16 h-16 bg-gradient-to-br from-deep-blue to-cyber-blue rounded-2xl flex items-center justify-center p-4 shadow-xl">
                            <ExternalLink className="text-white w-full h-full" />
                        </div>
                        <h1 className="text-4xl md:text-5xl font-black tracking-tight text-navy-900 dark:text-white">
                            Terms of <span className="text-transparent bg-clip-text bg-gradient-to-r from-deep-blue to-cyber-blue">Service</span>
                        </h1>
                    </div>

                    <div className="prose prose-lg dark:prose-invert max-w-none prose-headings:text-navy-900 dark:prose-headings:text-white prose-a:text-cyber-blue hover:prose-a:text-deep-blue transition-colors bg-white/50 dark:bg-navy-800/20 backdrop-blur-sm p-8 md:p-12 rounded-3xl border border-navy-200 dark:border-navy-700">
                        <p>By using BarcodesMaker.com, you agree to these Terms of Service. Our tools are provided "as-is" for professional and personal use without any express warranties.</p>

                        <h3>Usage Rights</h3>
                        <p>The barcodes and QR codes generated by our site are completely free for commercial and personal use. You may print, distribute, and integrate them into your packaging, marketing materials, and software. No attribution is required, though we always appreciate a mention or a backlink to our site.</p>

                        <h3>Limitations of Liability</h3>
                        <p>While we strive for 100% accuracy using industrial-grade libraries like <code>bwip-js</code>, errors may occur depending on the specific renderer, browser, and print quality. You are solely responsible for testing and verifying the readability of your printed labels before full-scale deployment or production runs. BarcodesMaker.com cannot be held liable for misprinted labels, unscannable codes, or any resulting financial losses.</p>

                        <h3>Acceptable Use</h3>
                        <p>You agree not to use our tool to generate barcodes for illegal activities, including counterfeiting or creating fraudulent promotional codes. Furthermore, automated scraping or overwhelming our service through automated HTTP requests without our permission is strictly prohibited.</p>

                        <h3>Modifications</h3>
                        <p>BarcodesMaker.com reserves the right to modify or discontinue the service (or any part or content thereof) without notice at any time.</p>

                        <p className="mt-8 text-sm text-navy-500 font-medium">Last Updated: October 2023</p>
                    </div>
                </div>
            </section>
        </React.Fragment>
    );
}
